# Generated by Django 5.0.6 on 2025-01-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0028_justificativamenos8horas_texto_justificando_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatoriosPlanilhas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_atribuicao', models.TextField(default='')),
                ('gerar_atribuicao', models.TextField(default='')),
                ('upload_preferencias', models.TextField(default='')),
                ('upload_rp1', models.TextField(default='')),
                ('upload_tadi', models.TextField(default='')),
            ],
        ),
    ]
