# Generated by Django 5.0.6 on 2025-02-17 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0029_relatoriosplanilhas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='NomeDisc',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
