# Generated by Django 5.0.6 on 2025-02-23 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0030_alter_disciplina_nomedisc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='TipoDisc',
            field=models.CharField(choices=[('obrigatoria', 'Obrigatória'), ('optativaCB', 'Optativa - Ciclo Básico'), ('optativaSI', 'Optativa - Sistemas de informação')], default='obrigatoria', max_length=12),
        ),
    ]
