# Generated by Django 5.0.6 on 2024-06-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aacc_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aacc",
            name="doc",
            field=models.FileField(upload_to="ferramentas/aacc_app/comprovantes_aac"),
        ),
    ]
