# Generated by Django 5.0.6 on 2024-06-03 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aacc_app", "0002_alter_aacc_doc"),
    ]

    operations = [
        migrations.AddField(
            model_name="aaccparaavaliacao",
            name="carga_aprovada",
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
    ]
