# Generated by Django 4.1.6 on 2024-06-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aacc_app", "0003_aaccparaavaliacao_carga_aprovada"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aacc",
            name="fim",
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name="aacc",
            name="inicio",
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name="aaccparaavaliacao",
            name="carga_aprovada",
            field=models.CharField(default=0, max_length=4),
        ),
    ]
