# Generated by Django 4.1.6 on 2024-06-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aacc_app", "0004_alter_aacc_fim_alter_aacc_inicio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aacc",
            name="fim",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="aacc",
            name="inicio",
            field=models.DateField(null=True),
        ),
    ]
